# Generated by Django 2.2.5 on 2019-10-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
